# Stage 1: Build Golang executable
FROM golang:alpine AS builder
WORKDIR /app

COPY ./sandboxes .

RUN go mod download

RUN go build -o runner ./node/sandbox.go

# Stage 2: Build Sandbox Image
FROM node:24-alpine
WORKDIR /app

COPY --from=builder /app/runner .

USER node

CMD ["./runner"]
