# Stage 1: Build Golang executable
FROM golang:alpine AS builder
WORKDIR /app

COPY ./sandboxes .

RUN go mod download

RUN go build -o runner ./c/sandbox.go

# Stage 2: Build Sandbox Image
FROM gcc:latest
WORKDIR /app

COPY --from=builder /app/runner .

RUN useradd -m sandbox
USER sandbox

CMD ["./runner"]
