worker_processes 1;

events { worker_connections 1024; }

http {
  sendfile on;
  map $http_origin $cors_origin {
    default "";
    "http://localhost:3000" $http_origin;
  }

  upstream app_servers {
    server opencodelab-app-server-1:3000;
    server opencodelab-app-server-2:3000;
    server opencodelab-app-server-3:3000;
    server opencodelab-app-server-4:3000;
    # Add more app-server instances here if needed
  }

  upstream polling_servers {
    server opencodelab-polling-server-1:8080;
    server opencodelab-polling-server-2:8080; 
  }

  server {
    listen 80;

    location /consumer {
      add_header "Access-Control-Allow-Origin" "$cors_origin" always;
      add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS" always;
      add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept" always;
      add_header "Access-Control-Allow-Credentials" "true" always;
      add_header "Vary" "Origin" always;

      if ($request_method = OPTIONS) {
        return 204;
      }

      proxy_pass http://polling_servers;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }
    
    location / {
      add_header "Access-Control-Allow-Origin" "$cors_origin" always;
      add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS" always;
      add_header "Access-Control-Allow-Headers" "Authorization, Origin, X-Requested-With, Content-Type, Accept" always;
      add_header "Access-Control-Allow-Credentials" "true" always;
      add_header "Vary" "Origin" always;

      if ($request_method = OPTIONS) {
        return 204;
      }

      proxy_pass http://app_servers;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection 'upgrade';
      proxy_set_header Host $host;
      proxy_cache_bypass $http_upgrade;
    }

  }
}
